# Generated by Django 2.2.6 on 2019-10-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '动作表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='p', to='RBAC.Menu')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RBAC.Menu')),
            ],
            options={
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='Permission2Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBAC.Action')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBAC.Permission')),
            ],
            options={
                'verbose_name_plural': '权限动作关系表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status_id', models.IntegerField(choices=[(0, '离职'), (1, '在职')], default=1)),
                ('userName', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='User2Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBAC.Role')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBAC.User')),
            ],
            options={
                'verbose_name_plural': '角色配置表',
            },
        ),
        migrations.CreateModel(
            name='Role2Permission2Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p2a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBAC.Permission2Action')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBAC.Role')),
            ],
            options={
                'verbose_name_plural': '角色分配权限表',
            },
        ),
    ]
