# Generated by Django 2.2.6 on 2019-10-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
